#vo=gpu
#gpu-api=opengl
hwdec=auto
sub-auto=fuzzy
ytdl-raw-options=sub-lang="en,pl",write-sub=,write-auto-sub=,cookies="C:\Users\Adiker\Desktop\cookies.txt"
slang=en
keep-open=always
watch-later-options=start
save-position-on-quit
osd-font-size=60
target-colorspace-hint=yes
image-subs-hdr-peak=80
sub-hdr-peak=80
sub-font='Open Sans'
